# dbt Project Configuration for Tokyo Beta Data Consolidation

name: 'tokyobeta_analytics'
version: '1.0.0'
config-version: 2

# Project profile (uses profiles.yml for connection details)
profile: 'tokyobeta'

# Model paths
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

# Build artifacts
target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

# Model configurations
models:
  tokyobeta_analytics:
    # Staging models (sources from bronze/raw data)
    staging:
      +materialized: view
      +schema: staging
      +tags: ["staging", "bronze"]
    
    # Silver layer (cleaned and enriched data)
    silver:
      +materialized: view
      +schema: silver
      +tags: ["silver", "intermediate"]
      # int_* models are tables for performance
      int_contracts:
        +materialized: table
    
    # Gold layer (BI-ready analytics tables)
    gold:
      +materialized: table
      +schema: gold
      +tags: ["gold", "dashboard"]
      +indexes:
        - type: btree
          columns: ['activity_date']

# Seeds configuration  
seeds:
  tokyobeta_analytics:
    +schema: seeds
    +tags: ["seeds", "reference"]
    # Code mapping seeds
    code_gender:
      +column_types:
        code: integer
        label_ja: varchar(50)
        label_en: varchar(50)
    code_tenant_status:
      +column_types:
        code: integer
        label_ja: varchar(100)
        label_en: varchar(100)
        is_active_lease: integer
    code_contract_type:
      +column_types:
        code: integer
        label_ja: varchar(100)
        label_en: varchar(100)
        tenant_type: varchar(20)
    code_personal_identity:
      +column_types:
        code: integer
        label_ja: varchar(100)
        label_en: varchar(100)
    code_affiliation_type:
      +column_types:
        code: integer
        label_ja: varchar(100)
        label_en: varchar(100)
    code_moveout_reason:
      +column_types:
        code: integer
        label_ja: varchar(100)
        label_en: varchar(100)
    # Legacy geocoding seed (if exists)
    asset_geocoding:
      +column_types:
        asset_id: integer
        latitude: decimal(8,6)
        longitude: decimal(9,6)

# Test configurations
tests:
  +store_failures: true
  +schema: test_results

# Documentation
docs-paths: ["docs"]

# Hooks
on-run-start:
  - "{{ log('Starting dbt run for Tokyo Beta Analytics', info=True) }}"
  
on-run-end:
  - "{{ log('Completed dbt run for Tokyo Beta Analytics', info=True) }}"

# Variables
vars:
  # Lookback period for moveout notices (months)
  moveout_notice_window_months: 24
  
  # Individual vs Corporate contract type mappings
  corporate_contract_types: [2, 3, 4]  # From m_systems or contract_type field
  
  # Date range for active data (avoid historical test data)
  min_valid_date: '2018-01-01'
