# dbt Profiles Configuration
# Connection settings for Aurora MySQL

tokyobeta:
  outputs:
    dev:
      type: mysql
      host: "{{ env_var('AURORA_ENDPOINT') }}"
      port: 3306
      user: "{{ env_var('AURORA_USERNAME') }}"
      password: "{{ env_var('AURORA_PASSWORD') }}"
      schema: tokyobeta
      threads: 4
      keepalives_idle: 0
      connect_timeout: 10
      
    prod:
      type: mysql
      host: "{{ env_var('AURORA_ENDPOINT') }}"
      port: 3306
      user: "{{ env_var('AURORA_USERNAME') }}"
      password: "{{ env_var('AURORA_PASSWORD') }}"
      database: tokyobeta
      threads: 8
      keepalives_idle: 0
      connect_timeout: 10
    
    local:
      type: mysql
      host: 127.0.0.1
      port: 3307
      user: root
      password: localdev
      schema: tokyobeta
      threads: 2
      keepalives_idle: 0
      connect_timeout: 10

  target: "{{ env_var('DBT_TARGET', 'dev') }}"
