# dbt Profiles Configuration
# Connection settings for Aurora MySQL

tokyobeta:
  outputs:
    dev:
      type: mysql
      host: "{{ env_var('AURORA_ENDPOINT') }}"
      port: 3306
      user: "{{ env_var('AURORA_USERNAME') }}"
      password: "{{ env_var('AURORA_PASSWORD') }}"
      database: tokyobeta
      schema: analytics
      threads: 4
      keepalives_idle: 0
      connect_timeout: 10
      
    prod:
      type: mysql
      host: "{{ env_var('AURORA_ENDPOINT') }}"
      port: 3306
      user: "{{ env_var('AURORA_USERNAME') }}"
      password: "{{ env_var('AURORA_PASSWORD') }}"
      database: tokyobeta
      schema: analytics
      threads: 8
      keepalives_idle: 0
      connect_timeout: 10

  target: "{{ env_var('DBT_TARGET', 'dev') }}"
